### ISSUE TITLE
Change UI border style

### ISSUE THREAD

**Issue by NiteshSaxena** [GleamTech/FileUltimate#3]
Hi,

I am looking to update the User Interface of File Ultimate. I am not able to style the border lines of the UI. I want to set the border to white with opacity of 20%. Is there a way I can do that?
Any help would be greatly appreciated.

**Comment by GleamTech** [comment]
Which borders are you speaking of? I guess you mean the toolbar button borders, then you can include this CSS override in the host page for that:

```css
.x-toolbar-default .x-btn {
    border-color: rgba(255, 255, 255, 0.8);
}
```
I tried 0.2 but it's hardly visible.
